#!/usr/bin/env node
// ═══ W4·H · THE TABLE CENSUS ══════════════════════════════════════════
// Documentation that cannot rot. Reads supabase/schema.sql, groups every
// table by territory, and writes the census block into ARCHITECTURE.md
// between its markers. `--check` fails (exit 1) when the written census
// disagrees with the schema — which is how a migration that forgets its
// documentation becomes a failing build rather than a stale paragraph.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const SCHEMA = join(root, "supabase", "schema.sql");
const DOC = join(root, "ARCHITECTURE.md");
const START = "<!-- CENSUS:START -->";
const END = "<!-- CENSUS:END -->";

// Territory ownership. Every table belongs to exactly one territory; a
// table absent from this map is reported as UNCLASSIFIED and fails --check,
// so new tables must declare where they live.
export const TERRITORIES = [
  ["Foundation", "Identity, permissions, settings, audit and notification plumbing.",
    ["users", "roles", "settings", "audit_log", "notifications", "departments", "files", "mail_log", "error_log",
     "sso_connections", "auth_events", "erasure_requests", "erasure_log"]],
  ["Campaigns & Planning", "The operating spine: campaigns, briefs, budget, objectives, tasks.",
    ["campaigns", "campaign_briefs", "campaign_items", "budget_entries", "objectives", "key_results", "tasks", "process_templates", "playbooks"]],
  ["Demand", "Leads, scoring, activity, customers and captured value.",
    ["leads", "lead_activities", "lead_score_rules", "customers", "conversions", "import_jobs"]],
  ["Audience", "Who the marketing is aimed at.",
    ["segments", "personas", "products", "contacts"]],
  ["Publish", "Content production, variants, scheduling and the public bio surface.",
    ["content_items", "content_variants", "scheduled_posts", "posts", "bio_pages", "bio_links", "social_accounts", "social_metrics", "seasonal_packs", "seasonal_events"]],
  ["Automate", "Trigger→condition→action workflows, forms, landing pages, messaging templates.",
    ["workflows", "workflow_runs", "forms", "form_submissions", "landing_pages", "wa_templates"]],
  ["Research", "Surveys, feedback and the insight ledger.",
    ["surveys", "survey_responses", "feedback", "insights"]],
  ["Reach", "Outreach sequences, media relations, influence and events.",
    ["outreach_campaigns", "outreach_touches", "media_contacts", "press_items", "coverage_reports", "influencers", "influencer_collabs", "events", "event_registrations"]],
  ["Studio & Agency", "Creative production and the client↔agency seam.",
    ["creative_requests", "creative_briefs", "brand_assets", "copy_bank", "assets", "asset_versions", "vendors", "engagements", "deliverables", "deliverable_comments", "invoices", "portal_tokens", "approvals", "approval_delegations"]],
  ["Analytics", "The measurement brain: catalog, snapshots, targets, alerts, boards, reports.",
    ["metrics", "metric_snapshots", "metric_targets", "metric_alerts", "dashboards", "report_runs", "digest_log"]],
  ["Connective Tissue", "Media plans, attribution, promotions, partners and first-party web analytics.",
    ["media_plans", "media_placements", "tracked_links", "promotions", "referrals", "partners", "partner_campaigns", "ad_spend", "sites", "web_events", "competitors", "inbox_items"]],
  ["Listening", "OSINT collection, validation, entities, evidence and the analyst's control room.",
    ["osint_topics", "osint_signals", "osint_sources", "osint_entities", "osint_aliases", "osint_signal_entities", "osint_cases", "osint_case_items", "osint_handle_candidates", "osint_themes", "osint_theme_signals", "listening_alert_rules", "listening_changes"]],
  ["Intelligence", "AI, live search and the quantitative models.",
    ["ai_runs", "ai_cache", "search_runs", "search_budget", "mmm_weeks", "mmm_runs"]],
  ["Integrations", "Third-party connectors and their run history.",
    ["integration_runs"]],
];

export function tablesInSchema(sql) {
  return [...sql.matchAll(/create table if not exists\s+(\w+)\s*\(/gi)].map((m) => m[1]);
}

export function buildCensus(tables) {
  const owned = new Map();
  for (const [territory, , list] of TERRITORIES) for (const t of list) owned.set(t, territory);
  const groups = new Map(TERRITORIES.map(([t, purpose]) => [t, { purpose, tables: [] }]));
  const unclassified = [];
  for (const t of tables.slice().sort()) {
    const territory = owned.get(t);
    if (!territory) { unclassified.push(t); continue; }
    groups.get(territory).tables.push(t);
  }
  const lines = [`**${tables.length} tables** across ${TERRITORIES.length} territories. Generated by \`npm run docs:census\` — do not edit by hand.`, ""];
  lines.push("| Territory | Tables | Purpose |", "|---|---|---|");
  for (const [name, { purpose, tables: ts }] of groups) {
    if (!ts.length) continue;
    lines.push(`| **${name}** (${ts.length}) | ${ts.map((t) => `\`${t}\``).join(" · ")} | ${purpose} |`);
  }
  if (unclassified.length) {
    lines.push("", `> ⚠️ **UNCLASSIFIED (${unclassified.length}):** ${unclassified.map((t) => `\`${t}\``).join(", ")} — add each to TERRITORIES in \`backend/scripts/census.js\`.`);
  }
  return { body: lines.join("\n"), unclassified, count: tables.length };
}

function main() {
  const check = process.argv.includes("--check");
  const tables = tablesInSchema(readFileSync(SCHEMA, "utf8"));
  const { body, unclassified, count } = buildCensus(tables);
  const doc = readFileSync(DOC, "utf8");
  const i = doc.indexOf(START), j = doc.indexOf(END);
  if (i === -1 || j === -1) { console.error(`✗ ARCHITECTURE.md is missing ${START} / ${END} markers`); process.exit(1); }
  const current = doc.slice(i + START.length, j).trim();
  if (check) {
    const problems = [];
    if (unclassified.length) problems.push(`${unclassified.length} unclassified table(s): ${unclassified.join(", ")}`);
    if (current !== body.trim()) problems.push("census block is stale — run `npm run docs:census`");
    if (problems.length) { console.error("✗ census check failed:\n  - " + problems.join("\n  - ")); process.exit(1); }
    console.log(`✓ census current — ${count} tables, all classified`);
    return;
  }
  writeFileSync(DOC, doc.slice(0, i + START.length) + "\n" + body + "\n" + doc.slice(j));
  console.log(`✓ census written — ${count} tables${unclassified.length ? `, ${unclassified.length} UNCLASSIFIED` : ""}`);
}

if (process.argv[1] && process.argv[1].endsWith("census.js")) main();
