import { useState } from "react";
import { Card, Empty, Field, Modal, SectionTitle, Select, StatusPill, useFetch } from "../components/ui";
import { useAuth } from "../context/AuthContext";
import { useI18n } from "../context/I18nContext";
import { useToast } from "../components/Toast";
import { api } from "../lib/api";
import { fmtDate } from "../lib/format";

type Tab = "privacy" | "identity" | "events" | "data-map";
interface PrivacyRequest { id: string; kind: string; subjectEmail?: string; subjectPhone?: string; subjectNote?: string; status: string; rejectReason?: string; requestedByName?: string; createdAt: string; inventory?: { total: number; tables: { table: string; rows: number }[] }; certificate?: Record<string, unknown>; log?: { tableName: string; action: string; at: string }[] }
interface PiiMap { table: string; mode: string; columns: string[]; keep?: string[]; note?: string }
interface SsoConnection { id: string; kind: string; name: string; issuerUrl: string; clientId: string; hasSecret: boolean; emailDomains: string[]; roleMap: Record<string, string>; defaultRole?: string; jitEnabled: boolean; ssoRequired: boolean; requireVerifiedEmail: boolean; active: boolean; discoveryAt?: string; jwksAt?: string }
interface AuthEvent { id: string; userName?: string; email?: string; method: string; ok: boolean; reason?: string; ip?: string; at: string }
interface Role { key: string; label: string }

export default function Governance() {
  const { lang } = useI18n(); const { can, isAdmin } = useAuth(); const [tab, setTab] = useState<Tab>(can("leads", "read") ? "privacy" : "identity");
  const tabs = [can("leads", "read") && { id: "privacy" as Tab, ar: "طلبات الخصوصية", en: "Privacy requests" }, isAdmin && { id: "identity" as Tab, ar: "الدخول الموحد", en: "Identity and SSO" }, isAdmin && { id: "events" as Tab, ar: "سجل الدخول", en: "Sign-in log" }, can("leads", "read") && { id: "data-map" as Tab, ar: "خريطة البيانات", en: "Data map" }].filter(Boolean) as { id: Tab; ar: string; en: string }[];
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold text-ink-900">{lang === "ar" ? "الحوكمة والخصوصية" : "Governance and Privacy"}</h1><p className="text-sm text-ink-500">{lang === "ar" ? "الهوية وطلبات أصحاب البيانات وأدلة التنفيذ" : "Identity, data-subject requests, and execution evidence"}</p></div><div className="flex flex-wrap gap-2">{tabs.map((x) => <button key={x.id} onClick={() => setTab(x.id)} className={tab === x.id ? "btn-amber" : "btn-ghost"}>{lang === "ar" ? x.ar : x.en}</button>)}</div>{tab === "privacy" && <Privacy />}{tab === "identity" && isAdmin && <Identity />}{tab === "events" && isAdmin && <SignInLog />}{tab === "data-map" && <DataMap />}</div>;
}

function Privacy() {
  const { lang, tr } = useI18n(); const { can, isAdmin } = useAuth(); const toast = useToast(); const rows = useFetch<PrivacyRequest[]>("/erasure"); const [form, setForm] = useState({ kind: "ERASURE", subjectEmail: "", subjectPhone: "", subjectNote: "" }); const [open, setOpen] = useState<PrivacyRequest | null>(null); const [result, setResult] = useState<Record<string, unknown> | null>(null);
  const create = async () => { try { await api.post("/erasure", form); setForm({ kind: "ERASURE", subjectEmail: "", subjectPhone: "", subjectNote: "" }); rows.reload(); } catch (e) { toast.push((e as Error).message, "error"); } };
  const detail = async (id: string) => { try { setOpen(await api.get<PrivacyRequest>(`/erasure/${id}`)); setResult(null); } catch (e) { toast.push((e as Error).message, "error"); } };
  const action = async (path: string, body: Record<string, unknown> = {}) => { if (!open) return; try { const out = await api.post<Partial<PrivacyRequest> & Record<string, unknown>>(`/erasure/${open.id}/${path}`, body); setOpen({ ...open, ...out }); setResult(out); rows.reload(); toast.push(tr("saved"), "success"); } catch (e) { toast.push((e as Error).message, "error"); } };
  const manual = async () => { const evidence = window.prompt("Record how identity was established"); if (evidence) action("verify/manual", { evidence }); };
  const reject = async () => { const reason = window.prompt("IDENTITY_UNVERIFIED, LEGAL_HOLD, DUPLICATE, or NOT_FOUND", "IDENTITY_UNVERIFIED"); if (reason) action("reject", { reason }); };
  const downloadResult = () => { if (!result) return; const url = URL.createObjectURL(new Blob([JSON.stringify(result, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = `privacy-request-${open?.id}.json`; a.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-4">{can("leads") && <Card><SectionTitle>{lang === "ar" ? "طلب جديد" : "New request"}</SectionTitle><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Select value={form.kind} onChange={(kind) => setForm({ ...form, kind })} options={[{ value: "ERASURE", label: "ERASURE" }, { value: "EXPORT", label: "EXPORT" }]} /><input className="input" type="email" dir="ltr" placeholder={tr("email")} value={form.subjectEmail} onChange={(e) => setForm({ ...form, subjectEmail: e.target.value })} /><input className="input" dir="ltr" placeholder={tr("phone")} value={form.subjectPhone} onChange={(e) => setForm({ ...form, subjectPhone: e.target.value })} /><input className="input" placeholder={tr("notes")} value={form.subjectNote} onChange={(e) => setForm({ ...form, subjectNote: e.target.value })} /><button onClick={create} disabled={!form.subjectEmail && !form.subjectPhone} className="btn-amber">{tr("save")}</button></div></Card>}
    <Card><SectionTitle action={isAdmin ? <button onClick={async () => { try { const x = await api.post<Record<string, unknown>>("/erasure/replay", {}); setResult(x); toast.push(tr("saved"), "success"); } catch (e) { toast.push((e as Error).message, "error"); } }} className="btn-ghost text-xs">{lang === "ar" ? "إعادة تطبيق بعد الاستعادة" : "Replay after restore"}</button> : undefined}>{lang === "ar" ? "سجل الطلبات" : "Request register"}</SectionTitle>{!rows.data?.length ? <Empty text={tr("noData")} /> : <div className="space-y-2">{rows.data.map((r) => <button key={r.id} onClick={() => detail(r.id)} className="flex w-full flex-wrap items-center justify-between gap-2 rounded-xl border border-paper-200 p-3 text-start hover:bg-paper-100"><span><b className="text-sm text-ink-800">{r.subjectEmail || r.subjectPhone}</b><span className="ms-2 text-xs text-ink-400">{r.kind} · {fmtDate(r.createdAt, lang)}</span></span><StatusPill value={r.status} /></button>)}</div>}</Card>
    <Modal open={!!open} onClose={() => setOpen(null)} title={open?.subjectEmail || open?.subjectPhone || "Privacy request"}>{open && <div className="space-y-4"><div className="flex items-center justify-between"><StatusPill value={open.status} /><span className="text-xs text-ink-400">{open.kind}</span></div>{open.subjectNote && <p className="text-sm text-ink-600">{open.subjectNote}</p>}{open.inventory && <div className="rounded-xl bg-paper-100 p-3"><b className="text-sm">{open.inventory.total} records</b><div className="mt-2 space-y-1">{open.inventory.tables.map((t) => <div key={t.table} className="flex justify-between text-xs"><span>{t.table}</span><span className="kpi-num">{t.rows}</span></div>)}</div></div>}{open.certificate && <pre className="max-h-52 overflow-auto rounded-lg bg-ink-950 p-3 text-[10px] text-paper-100" dir="ltr">{JSON.stringify(open.certificate, null, 2)}</pre>}
      {can("leads") && <div className="flex flex-wrap gap-2">{open.status === "RECEIVED" && open.subjectEmail && <button onClick={() => action("verify/send")} className="btn-ghost text-xs">{lang === "ar" ? "إرسال التحقق" : "Send verification"}</button>}{open.status === "RECEIVED" && isAdmin && <button onClick={manual} className="btn-ghost text-xs">{lang === "ar" ? "تحقق يدوي" : "Manual verification"}</button>}{open.status === "VERIFIED" && <button onClick={() => action("discover")} className="btn-ghost text-xs">{lang === "ar" ? "اكتشاف البيانات" : "Discover data"}</button>}{open.status === "DISCOVERED" && <button onClick={() => action("submit")} className="btn-ghost text-xs">{lang === "ar" ? "تقديم للموافقة" : "Submit for approval"}</button>}{open.status === "PENDING_APPROVAL" && isAdmin && <button onClick={() => action("execute")} className="btn-amber text-xs">{open.kind === "EXPORT" ? (lang === "ar" ? "تصدير" : "Export") : (lang === "ar" ? "تنفيذ المحو" : "Execute erasure")}</button>}{!["CONFIRMED", "REJECTED"].includes(open.status) && <button onClick={reject} className="btn-ghost text-xs text-clay-600">{lang === "ar" ? "رفض" : "Reject"}</button>}</div>}{result && <button onClick={downloadResult} className="btn-ghost text-xs">{lang === "ar" ? "تنزيل الدليل" : "Download evidence"}</button>}</div>}</Modal>
  </div>;
}

function Identity() {
  const { lang, tr } = useI18n(); const toast = useToast(); const rows = useFetch<SsoConnection[]>("/sso"); const roles = useFetch<Role[]>("/roles"); const [form, setForm] = useState({ name: "Corporate SSO", issuerUrl: "", clientId: "", clientSecret: "", emailDomains: "", defaultRole: "", jitEnabled: false, requireVerifiedEmail: true }); const [test, setTest] = useState<Record<string, unknown> | null>(null);
  const create = async () => { try { await api.post("/sso", { ...form, emailDomains: form.emailDomains.split(",").map((x) => x.trim()).filter(Boolean) }); setForm({ name: "Corporate SSO", issuerUrl: "", clientId: "", clientSecret: "", emailDomains: "", defaultRole: "", jitEnabled: false, requireVerifiedEmail: true }); rows.reload(); } catch (e) { toast.push((e as Error).message, "error"); } };
  const patch = async (id: string, body: Record<string, unknown>) => { try { await api.patch(`/sso/${id}`, body); rows.reload(); } catch (e) { toast.push((e as Error).message, "error"); } };
  return <div className="space-y-4"><Card><SectionTitle>{lang === "ar" ? "اتصال OIDC جديد" : "New OIDC connection"}</SectionTitle><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input className="input" placeholder={tr("name")} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input className="input" dir="ltr" placeholder="https://issuer.example" value={form.issuerUrl} onChange={(e) => setForm({ ...form, issuerUrl: e.target.value })} /><input className="input" dir="ltr" placeholder="clientId" value={form.clientId} onChange={(e) => setForm({ ...form, clientId: e.target.value })} /><input className="input" type="password" dir="ltr" placeholder="clientSecret" value={form.clientSecret} onChange={(e) => setForm({ ...form, clientSecret: e.target.value })} /><input className="input" dir="ltr" placeholder="example.com, example.org" value={form.emailDomains} onChange={(e) => setForm({ ...form, emailDomains: e.target.value })} /><Select value={form.defaultRole} onChange={(defaultRole) => setForm({ ...form, defaultRole })} placeholder={lang === "ar" ? "الدور الافتراضي" : "Default role"} options={(roles.data || []).map((r) => ({ value: r.key, label: r.label }))} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.jitEnabled} onChange={(e) => setForm({ ...form, jitEnabled: e.target.checked })} />JIT</label><button onClick={create} disabled={!form.issuerUrl || !form.clientId} className="btn-amber">{tr("save")}</button></div></Card>
    <div className="grid gap-3 md:grid-cols-2">{(rows.data || []).map((c) => <Card key={c.id}><div className="flex items-start justify-between"><div><h3 className="font-semibold text-ink-800">{c.name}</h3><p className="mt-1 break-all text-xs text-ink-500" dir="ltr">{c.issuerUrl}</p></div><StatusPill value={c.active ? "ACTIVE" : "PAUSED"} /></div><div className="mt-3 flex flex-wrap gap-3 text-xs text-ink-500"><span>{c.hasSecret ? "secret set" : "no secret"}</span><span>JIT {c.jitEnabled ? "on" : "off"}</span><span>SSO required {c.ssoRequired ? "on" : "off"}</span></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={() => patch(c.id, { active: !c.active })} className="btn-ghost text-xs">{c.active ? (lang === "ar" ? "تعطيل" : "Deactivate") : (lang === "ar" ? "تفعيل" : "Activate")}</button><button onClick={() => patch(c.id, { jitEnabled: !c.jitEnabled })} className="btn-ghost text-xs">JIT</button><button onClick={() => patch(c.id, { ssoRequired: !c.ssoRequired })} className="btn-ghost text-xs">{lang === "ar" ? "إلزام SSO" : "Require SSO"}</button><button onClick={async () => { try { setTest(await api.post(`/sso/${c.id}/test`, {})); } catch (e) { toast.push((e as Error).message, "error"); } }} className="btn-ghost text-xs">{lang === "ar" ? "اختبار" : "Test"}</button><button onClick={async () => { if (confirm(tr("confirmDelete"))) { await api.del(`/sso/${c.id}`); rows.reload(); } }} className="btn-ghost text-xs text-clay-600">{tr("delete")}</button></div></Card>)}</div>{test && <pre className="max-h-56 overflow-auto rounded-xl bg-ink-950 p-3 text-[10px] text-paper-100" dir="ltr">{JSON.stringify(test, null, 2)}</pre>}</div>;
}

function SignInLog() {
  const { lang, tr } = useI18n(); const rows = useFetch<AuthEvent[]>("/sso/events?limit=200");
  return <Card className="overflow-x-auto p-0">{!rows.data?.length ? <Empty text={tr("noData")} /> : <table className="w-full text-sm"><thead><tr className="border-b text-xs text-ink-500"><th className="p-3 text-start">{tr("date")}</th><th className="p-3 text-start">{tr("email")}</th><th className="p-3 text-start">Method</th><th className="p-3 text-start">{tr("status")}</th><th className="p-3 text-start">Reason</th></tr></thead><tbody>{rows.data.map((e) => <tr key={e.id} className="border-b border-paper-100"><td className="p-3">{fmtDate(e.at, lang)}</td><td className="p-3" dir="ltr">{e.email || e.userName || "—"}</td><td className="p-3">{e.method}</td><td className="p-3"><span className={`pill ${e.ok ? "bg-moss-500/12 text-moss-700" : "bg-clay-500/12 text-clay-600"}`}>{e.ok ? "OK" : "FAILED"}</span></td><td className="p-3 text-xs text-ink-500">{e.reason || "—"}</td></tr>)}</tbody></table>}</Card>;
}

function DataMap() {
  const { lang, tr } = useI18n(); const rows = useFetch<PiiMap[]>("/erasure/map");
  return <div className="grid gap-3 md:grid-cols-2">{!rows.data?.length ? <Card><Empty text={tr("noData")} /></Card> : rows.data.map((m) => <Card key={m.table}><div className="flex items-center justify-between"><b className="font-mono text-sm text-ink-800">{m.table}</b><span className="pill bg-steel-500/12 text-steel-600">{m.mode}</span></div><p className="mt-2 text-xs text-ink-500">{m.columns.join(" · ")}</p>{m.note && <p className="mt-2 text-xs text-ink-400">{m.note}</p>}</Card>)}</div>;
}
