import { useState } from "react";
import { Card, Empty, Field, Modal, SectionTitle, Select, StatusPill, useFetch } from "../components/ui";
import { useAuth } from "../context/AuthContext";
import { useI18n } from "../context/I18nContext";
import { useToast } from "../components/Toast";
import { api } from "../lib/api";
import { fmtDate, fmtMoney } from "../lib/format";

type Tab = "imports" | "value" | "followup" | "templates" | "season";
interface ImportTarget { entity: string; required: string[]; fields: string[] }
interface ImportJob { id: string; entity: string; status: string; filename?: string; header?: string[]; mapping?: Record<string, string>; stats?: Record<string, number>; errors?: { row: number; reason: string }[]; suggestedMapping?: Record<string, string>; sampleRows?: string[][]; createdAt?: string }
interface Conversion { id: string; leadId?: string; leadCompany?: string; campaignName?: string; valueAmount: number; valueUsd: number; currency: string; occurredOn: string; kind: string }
interface Summary { windowDays: number; spendUsd: number; valueUsd: number; roiPct: number | null; byCampaign: { name: string; valueUsd: number; n: number }[] }
interface Due { id: string; company: string; ownerId?: string; ownerName?: string; followUpDueAt: string; slaBreached: boolean; overdue: boolean }
interface Lead { id: string; company: string; ownerId?: string }
interface User { id: string; name: string }
interface Template { id: string; kind: string; name: string; nameAr?: string; description?: string; descriptionAr?: string; builtin: boolean }
interface Pack { id: string; key: string; name: string; nameAr?: string; region?: string; events: SeasonEvent[] }
interface SeasonEvent { id: string; key: string; name: string; nameAr?: string; calendar: string; month?: number; day?: number; onDate?: string }

export default function Operations() {
  const { lang, tr } = useI18n();
  const { can, isAdmin } = useAuth();
  const [tab, setTab] = useState<Tab>("imports");
  const tabs: { id: Tab; label: string }[] = [
    { id: "imports", label: lang === "ar" ? "الاستيراد" : "Imports" }, { id: "value", label: lang === "ar" ? "القيمة" : "Conversions" },
    { id: "followup", label: lang === "ar" ? "المتابعة" : "Follow-up" }, { id: "templates", label: lang === "ar" ? "القوالب" : "Templates" },
    { id: "season", label: lang === "ar" ? "المواسم" : "Seasonal" },
  ];
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold text-ink-900">{lang === "ar" ? "مركز العمليات" : "Operations Center"}</h1><p className="text-sm text-ink-500">{lang === "ar" ? "البيانات والقيمة والمتابعة والقوالب والمواسم في مساراتها المعتمدة" : "Data, value, follow-up, templates, and seasonal planning through their governed workflows"}</p></div>
    <div className="flex flex-wrap gap-2">{tabs.map((x) => <button key={x.id} onClick={() => setTab(x.id)} className={tab === x.id ? "btn-amber" : "btn-ghost"}>{x.label}</button>)}</div>
    {tab === "imports" && can("leads", "read") && <Imports />}{tab === "value" && can("leads", "read") && <Conversions />}{tab === "followup" && can("leads", "read") && <FollowUp />}{tab === "templates" && <Templates />}{tab === "season" && <Seasonal admin={isAdmin} />}
  </div>;
}

function Imports() {
  const { lang, tr } = useI18n(); const { can } = useAuth(); const toast = useToast();
  const targets = useFetch<ImportTarget[]>("/imports/targets"); const jobs = useFetch<ImportJob[]>("/imports");
  const [upload, setUpload] = useState({ entity: "leads", filename: "", csv: "" }); const [job, setJob] = useState<ImportJob | null>(null); const [busy, setBusy] = useState(false);
  const open = async (id: string) => { try { setJob(await api.get(`/imports/${id}`)); } catch (e) { toast.push((e as Error).message, "error"); } };
  const create = async () => { setBusy(true); try { const j = await api.post<ImportJob>("/imports", upload); setJob({ ...j, mapping: j.suggestedMapping || j.mapping }); jobs.reload(); } catch (e) { toast.push((e as Error).message, "error"); } finally { setBusy(false); } };
  const act = async (kind: string) => { if (!job) return; setBusy(true); try {
    let next: ImportJob;
    if (kind === "mapping") next = await api.patch(`/imports/${job.id}/mapping`, { mapping: job.mapping || {}, dedupeOn: "email", mergeStrategy: "merge", consentBasis: "LEGITIMATE_INTEREST", consentSource: "IMPORT" });
    else next = await api.post(`/imports/${job.id}/${kind}`, {});
    if (kind === "cancel") next = { ...job, status: "CANCELLED" };
    setJob(next); jobs.reload(); toast.push(tr("saved"), "success");
  } catch (e) { toast.push((e as Error).message, "error"); } finally { setBusy(false); } };
  return <div className="grid gap-5 lg:grid-cols-[1fr_1.3fr]">
    <div className="space-y-4"><Card><SectionTitle>{lang === "ar" ? "ملف جديد" : "New import"}</SectionTitle><div className="space-y-3"><Field label={lang === "ar" ? "الوجهة" : "Target"}><Select value={upload.entity} onChange={(entity) => setUpload({ ...upload, entity })} options={(targets.data || []).map((x) => ({ value: x.entity, label: x.entity }))} /></Field><Field label={lang === "ar" ? "اسم الملف" : "Filename"}><input className="input" value={upload.filename} onChange={(e) => setUpload({ ...upload, filename: e.target.value })} /></Field><Field label="CSV"><textarea className="input min-h-40 font-mono text-xs" dir="ltr" value={upload.csv} onChange={(e) => setUpload({ ...upload, csv: e.target.value })} /></Field>{can("leads") && <button onClick={create} disabled={busy || !upload.csv.trim()} className="btn-amber w-full">{lang === "ar" ? "رفع وفحص العناوين" : "Upload and inspect"}</button>}</div></Card>
      <Card><SectionTitle>{lang === "ar" ? "السجل" : "Import history"}</SectionTitle>{!jobs.data?.length ? <Empty text={tr("noData")} /> : <div className="space-y-1">{jobs.data.map((j) => <button key={j.id} onClick={() => open(j.id)} className="flex w-full items-center justify-between rounded-lg px-2 py-2 text-start hover:bg-paper-100"><span><b className="text-sm text-ink-700">{j.filename || j.entity}</b><span className="ms-2 text-[11px] text-ink-400">{fmtDate(j.createdAt, lang)}</span></span><StatusPill value={j.status} /></button>)}</div>}</Card></div>
    <Card><SectionTitle>{lang === "ar" ? "مسار الاستيراد" : "Import workflow"}</SectionTitle>{!job ? <Empty text={lang === "ar" ? "اختر عملية أو ارفع ملفًا" : "Select an import or upload a file"} /> : <div className="space-y-4"><div className="flex items-center justify-between"><div><b>{job.filename || job.entity}</b><div className="text-xs text-ink-400">{job.entity}</div></div><StatusPill value={job.status} /></div>
      {job.header && <div className="space-y-2">{(targets.data?.find((x) => x.entity === job.entity)?.fields || []).map((field) => <div key={field} className="grid grid-cols-2 items-center gap-2"><span className="font-mono text-xs text-ink-600">{field}</span><Select value={job.mapping?.[field] || ""} onChange={(v) => setJob({ ...job, mapping: { ...job.mapping, [field]: v } })} placeholder="—" options={job.header!.map((h) => ({ value: h, label: h }))} /></div>)}</div>}
      {job.stats && <div className="grid grid-cols-3 gap-2">{Object.entries(job.stats).map(([k, v]) => <div key={k} className="rounded-lg bg-paper-100 p-2 text-center"><div className="kpi-num text-lg">{v}</div><div className="text-[10px] text-ink-500">{k}</div></div>)}</div>}
      {!!job.errors?.length && <div className="max-h-32 overflow-auto rounded-lg bg-clay-500/5 p-2 text-xs text-clay-700">{job.errors.map((e) => <div key={`${e.row}-${e.reason}`}>#{e.row}: {e.reason}</div>)}</div>}
      {can("leads") && <div className="flex flex-wrap gap-2">{["UPLOADED", "MAPPED", "VALIDATED", "PREVIEWED", "FAILED"].includes(job.status) && <button disabled={busy} onClick={() => act("mapping")} className="btn-ghost">1. {lang === "ar" ? "تثبيت المطابقة" : "Confirm mapping"}</button>}{job.status === "MAPPED" && <button disabled={busy} onClick={() => act("validate")} className="btn-ghost">2. {lang === "ar" ? "تحقق" : "Validate"}</button>}{job.status === "VALIDATED" && <button disabled={busy} onClick={() => act("preview")} className="btn-ghost">3. {lang === "ar" ? "معاينة" : "Preview"}</button>}{job.status === "PREVIEWED" && <button disabled={busy} onClick={() => act("commit")} className="btn-amber">4. {lang === "ar" ? "تنفيذ" : "Commit"}</button>}{!["COMMITTED", "CANCELLED"].includes(job.status) && <button disabled={busy} onClick={() => act("cancel")} className="btn-ghost text-clay-600">{tr("cancel")}</button>}</div>}
    </div>}</Card>
  </div>;
}

function Conversions() {
  const { lang, tr } = useI18n(); const { can } = useAuth(); const toast = useToast();
  const rows = useFetch<Conversion[]>("/conversions"); const summary = useFetch<Summary>("/conversions/summary"); const leads = useFetch<Lead[]>("/leads");
  const [form, setForm] = useState({ leadId: "", valueAmount: "", currency: "USD", occurredOn: "", kind: "SALE", notes: "" });
  const create = async () => { try { await api.post("/conversions", { ...form, valueAmount: Number(form.valueAmount), occurredOn: form.occurredOn || undefined }); setForm({ leadId: "", valueAmount: "", currency: "USD", occurredOn: "", kind: "SALE", notes: "" }); rows.reload(); summary.reload(); } catch (e) { toast.push((e as Error).message, "error"); } };
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Metric label={lang === "ar" ? "قيمة 90 يومًا" : "90-day value"} value={fmtMoney(summary.data?.valueUsd || 0, "USD", lang)} /><Metric label={tr("an_spend")} value={fmtMoney(summary.data?.spendUsd || 0, "USD", lang)} /><Metric label="ROI" value={summary.data?.roiPct == null ? "—" : `${summary.data.roiPct}%`} /></div>
    {can("leads") && <Card><SectionTitle>{lang === "ar" ? "تسجيل تحويل" : "Record conversion"}</SectionTitle><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Field label={tr("nav_leads")}><Select value={form.leadId} onChange={(leadId) => setForm({ ...form, leadId })} placeholder={tr("none")} options={(leads.data || []).map((l) => ({ value: l.id, label: l.company }))} /></Field><Field label={tr("value")}><input className="input" type="number" value={form.valueAmount} onChange={(e) => setForm({ ...form, valueAmount: e.target.value })} /></Field><Field label={lang === "ar" ? "العملة" : "Currency"}><input className="input" value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value.toUpperCase() })} /></Field><Field label={tr("date")}><input className="input" type="date" value={form.occurredOn} onChange={(e) => setForm({ ...form, occurredOn: e.target.value })} /></Field><Field label={lang === "ar" ? "النوع" : "Kind"}><input className="input" value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value })} /></Field><button onClick={create} disabled={!form.leadId || !form.valueAmount} className="btn-amber self-end">{tr("save")}</button></div></Card>}
    <Card className="overflow-x-auto p-0"><table className="w-full text-sm"><thead><tr className="border-b text-xs text-ink-500"><th className="p-3 text-start">{tr("date")}</th><th className="p-3 text-start">{tr("nav_leads")}</th><th className="p-3 text-start">{tr("campaign")}</th><th className="p-3 text-start">{tr("value")}</th><th /></tr></thead><tbody>{(rows.data || []).map((r) => <tr key={r.id} className="border-b border-paper-100"><td className="p-3">{fmtDate(r.occurredOn, lang)}</td><td className="p-3">{r.leadCompany || "—"}</td><td className="p-3">{r.campaignName || "—"}</td><td className="p-3 kpi-num">{fmtMoney(r.valueUsd, "USD", lang)}</td><td className="p-3 text-end">{can("leads") && <button onClick={async () => { await api.del(`/conversions/${r.id}`); rows.reload(); summary.reload(); }} className="text-xs text-clay-600">{tr("delete")}</button>}</td></tr>)}</tbody></table></Card></div>;
}

function FollowUp() {
  const { lang, tr } = useI18n(); const { can } = useAuth(); const toast = useToast(); const due = useFetch<Due[]>("/leads/due"); const leads = useFetch<Lead[]>("/leads"); const users = useFetch<User[]>("/users");
  const [assign, setAssign] = useState({ leadId: "", ownerId: "", slaHours: "48" });
  const assignLead = async () => { try { await api.post(`/leads/${assign.leadId}/assign`, { ownerId: assign.ownerId || undefined, slaHours: Number(assign.slaHours) }); due.reload(); toast.push(tr("saved"), "success"); } catch (e) { toast.push((e as Error).message, "error"); } };
  return <div className="space-y-4">{can("leads") && <Card><SectionTitle>{lang === "ar" ? "إسناد وبدء مهلة المتابعة" : "Assign and start follow-up SLA"}</SectionTitle><div className="grid gap-3 sm:grid-cols-4"><Select value={assign.leadId} onChange={(leadId) => setAssign({ ...assign, leadId })} placeholder={tr("nav_leads")} options={(leads.data || []).map((l) => ({ value: l.id, label: l.company }))} /><Select value={assign.ownerId} onChange={(ownerId) => setAssign({ ...assign, ownerId })} placeholder={tr("owner")} options={(users.data || []).map((u) => ({ value: u.id, label: u.name }))} /><input className="input" type="number" value={assign.slaHours} onChange={(e) => setAssign({ ...assign, slaHours: e.target.value })} /><button onClick={assignLead} disabled={!assign.leadId} className="btn-amber">{lang === "ar" ? "إسناد" : "Assign"}</button></div></Card>}
    <Card><SectionTitle>{lang === "ar" ? "المتابعات المفتوحة" : "Open follow-ups"}</SectionTitle>{!due.data?.length ? <Empty text={tr("noData")} /> : <div className="space-y-2">{due.data.map((d) => <div key={d.id} className={`flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3 ${d.overdue ? "border-clay-500/30 bg-clay-500/5" : "border-paper-200"}`}><div><b className="text-sm text-ink-800">{d.company}</b><div className="text-xs text-ink-500">{d.ownerName || tr("unassigned")} · {fmtDate(d.followUpDueAt, lang)}</div></div><div className="flex items-center gap-2">{d.slaBreached && <span className="pill bg-clay-500/12 text-clay-600">SLA</span>}{can("leads") && <button onClick={async () => { await api.post(`/leads/${d.id}/contacted`, {}); due.reload(); }} className="btn-ghost text-xs">{lang === "ar" ? "تم التواصل" : "Mark contacted"}</button>}</div></div>)}</div>}</Card></div>;
}

function Templates() {
  const { lang, tr } = useI18n(); const { can } = useAuth(); const toast = useToast(); const templates = useFetch<Template[]>("/templates/library"); const [using, setUsing] = useState<Template | null>(null); const [name, setName] = useState("");
  const use = async () => { if (!using) return; try { await api.post(`/templates/library/${using.id}/use`, { name: name || undefined }); setUsing(null); toast.push(tr("saved"), "success"); } catch (e) { toast.push((e as Error).message, "error"); } };
  return <><div className="grid gap-3 md:grid-cols-2">{(templates.data || []).map((t) => <Card key={t.id}><div className="flex items-start justify-between gap-2"><div><span className="pill bg-steel-500/12 text-steel-600">{t.kind}</span><h3 className="mt-2 font-semibold text-ink-800">{lang === "ar" && t.nameAr ? t.nameAr : t.name}</h3><p className="mt-1 text-xs text-ink-500">{lang === "ar" && t.descriptionAr ? t.descriptionAr : t.description}</p></div>{can("campaigns") && <button onClick={() => { setUsing(t); setName(""); }} className="btn-ghost text-xs">{lang === "ar" ? "استخدام" : "Use"}</button>}</div></Card>)}</div><Modal open={!!using} onClose={() => setUsing(null)} title={lang === "ar" ? "استخدام القالب" : "Use template"} footer={<><button onClick={() => setUsing(null)} className="btn-ghost">{tr("cancel")}</button><button onClick={use} className="btn-amber">{tr("save")}</button></>}><Field label={tr("name")}><input className="input" value={name} onChange={(e) => setName(e.target.value)} placeholder={using?.name} /></Field></Modal></>;
}

function Seasonal({ admin }: { admin: boolean }) {
  const { lang, tr } = useI18n(); const toast = useToast(); const packs = useFetch<Pack[]>("/seasonal"); const [pack, setPack] = useState({ key: "", name: "", nameAr: "", region: "" }); const [event, setEvent] = useState({ packId: "", key: "", name: "", nameAr: "", calendar: "GREGORIAN", month: "", day: "", onDate: "" }); const [hijriDate, setHijriDate] = useState(""); const [hijri, setHijri] = useState("");
  const createPack = async () => { try { await api.post("/seasonal", pack); setPack({ key: "", name: "", nameAr: "", region: "" }); packs.reload(); } catch (e) { toast.push((e as Error).message, "error"); } };
  const createEvent = async () => { try { await api.post(`/seasonal/${event.packId}/events`, { ...event, month: event.month ? Number(event.month) : undefined, day: event.day ? Number(event.day) : undefined, onDate: event.onDate || undefined }); setEvent({ packId: "", key: "", name: "", nameAr: "", calendar: "GREGORIAN", month: "", day: "", onDate: "" }); packs.reload(); } catch (e) { toast.push((e as Error).message, "error"); } };
  return <div className="space-y-4"><Card><SectionTitle>{lang === "ar" ? "التحويل الهجري" : "Hijri conversion"}</SectionTitle><div className="flex gap-2"><input className="input max-w-52" type="date" value={hijriDate} onChange={(e) => setHijriDate(e.target.value)} /><button onClick={async () => { const x = await api.get<{ hijri: { year: number; month: number; day: number } }>(`/calendar/hijri?date=${hijriDate}`); setHijri(`${x.hijri.year}-${x.hijri.month}-${x.hijri.day}`); }} className="btn-ghost">{lang === "ar" ? "تحويل" : "Convert"}</button><span className="self-center kpi-num">{hijri}</span></div></Card>
    {admin && <div className="grid gap-4 lg:grid-cols-2"><Card><SectionTitle>{lang === "ar" ? "حزمة موسمية" : "Seasonal pack"}</SectionTitle><div className="grid grid-cols-2 gap-2"><input className="input" placeholder="key" value={pack.key} onChange={(e) => setPack({ ...pack, key: e.target.value })} /><input className="input" placeholder="Name" value={pack.name} onChange={(e) => setPack({ ...pack, name: e.target.value })} /><input className="input" placeholder="الاسم" value={pack.nameAr} onChange={(e) => setPack({ ...pack, nameAr: e.target.value })} /><input className="input" placeholder="Region" value={pack.region} onChange={(e) => setPack({ ...pack, region: e.target.value })} /></div><button onClick={createPack} className="btn-amber mt-3">{tr("save")}</button></Card><Card><SectionTitle>{lang === "ar" ? "مناسبة" : "Seasonal event"}</SectionTitle><div className="grid grid-cols-2 gap-2"><Select value={event.packId} onChange={(packId) => setEvent({ ...event, packId })} placeholder={lang === "ar" ? "الحزمة" : "Pack"} options={(packs.data || []).map((p) => ({ value: p.id, label: p.name }))} /><Select value={event.calendar} onChange={(calendar) => setEvent({ ...event, calendar })} options={["GREGORIAN", "HIJRI", "EXPLICIT"].map((x) => ({ value: x, label: x }))} /><input className="input" placeholder="key" value={event.key} onChange={(e) => setEvent({ ...event, key: e.target.value })} /><input className="input" placeholder="Name" value={event.name} onChange={(e) => setEvent({ ...event, name: e.target.value })} />{event.calendar === "EXPLICIT" ? <input className="input col-span-2" type="date" value={event.onDate} onChange={(e) => setEvent({ ...event, onDate: e.target.value })} /> : <><input className="input" type="number" placeholder="Month" value={event.month} onChange={(e) => setEvent({ ...event, month: e.target.value })} /><input className="input" type="number" placeholder="Day" value={event.day} onChange={(e) => setEvent({ ...event, day: e.target.value })} /></>}</div><button onClick={createEvent} className="btn-amber mt-3">{tr("save")}</button></Card></div>}
    <div className="grid gap-3 md:grid-cols-2">{(packs.data || []).map((p) => <Card key={p.id}><SectionTitle>{lang === "ar" && p.nameAr ? p.nameAr : p.name}</SectionTitle><div className="space-y-2">{p.events.map((e) => <div key={e.id} className="flex items-center justify-between gap-2 rounded-lg bg-paper-100 p-2"><span className="text-sm text-ink-700">{lang === "ar" && e.nameAr ? e.nameAr : e.name} <span className="text-[10px] text-ink-400">{e.calendar} {e.onDate || `${e.month}/${e.day}`}</span></span>{admin && <button onClick={async () => { await api.del(`/seasonal/events/${e.id}`); packs.reload(); }} className="text-xs text-clay-600">{tr("delete")}</button>}</div>)}</div></Card>)}</div></div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <Card><div className="text-xs text-ink-500">{label}</div><div className="kpi-num mt-1 text-2xl text-ink-900">{value}</div></Card>; }
